# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save _build_ artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'ci --production'
  displayName: 'install dependences'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run _build_'
  displayName: '_build_ bundle'

